apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test
  labels:
    app: k8s-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test
  template:
    metadata:
      labels:
        app: k8s-test
    spec:
      containers:
      - name: k8s-test
        image: geoffreysakora/k8s-test:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 150m
            memory: 300Mi
          limits:
            cpu: 300m
            memory: 400Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
